### ISSUE TITLE
Report Decay

### ISSUE THREAD

**Issue by joebayles** [Esri/squad-leader-android#106]
Add a "decay" feature where old information just goes away after a specified amount of time. This is a feature that is currently in place in FBCB2 for several entities, old SPOTREPs (Spot Reports) for example.

When I spot the enemy and submit that report, it will decay over time. It's represented graphically by transparency (it shouldn't gray out since color is an important part of the symbology representation). An example time period would be:

| Age of Report | Opacity |
| :-: | --: |
| 0-60 minutes | 100% |
| 60-120 minutes | 75% |
| 120-240 minutes | 50% |
| 240-480 minutes | 25% |
| 480+ minutes | 0% |

The report is either deleted or has no symbology after eight hours.

_Additionally a message could be initiated to move that report to another table (history), but the intent is to remove it from the Current Situation._

It's important to note that any enemy contact that is confirmed should be represented persistently.

_This enhancement issue started in https://github.com/Esri/squad-leader-android/issues/98#issuecomment-77266731._

**Comment by joebayles** [comment]
@garys-esri did you ever review this enhancement?

**Comment by garys-esri** [comment]
@joebayles, I reviewed it but did not take action.

**Comment by joebayles** [comment]
No worries... assigning to the new template owner.

**Comment by joebayles** [comment]
Mature Support
