### ISSUE TITLE
Squad Leader 3.0.0 Product Owner Review

### ISSUE THREAD

**Issue by jrweakland** [Esri/squad-leader-android#117]
I used a Samsung Galaxy S4 - Model Number SCH-1545 on Android version 5.0.1 for the review. The Squad Leader version was downloaded from: https://esri.app.box.com/s/9hv7urwcvzisn67lyvfps855l8lediic

- [x] I would place <b>Setup</b> before <b>Usage</b> at https://github.com/Esri/squad-leader-android/blob/master/documentation/UserGuide.md <b>Usage</b> firstseems like more of a natural flow.
- [x] The app crashes when I attempt to send a spot report.
- [x] I have seen the same issues as #115.

**Comment by garys-esri** [comment]
@jrweakland, at what point in the spot report creation process does the app crash? Is it when you tap the map, when you change field values in the form, when you submit the form, or some other time? This is going to be tricky because spot reports work fine on all three of my devices of different models.

The other items you mentioned make sense and I can fix them soon.

**Comment by garys-esri** [comment]
Setup and Usage sections swapped in fd279411043845fe142cba3f1a57858c4dd51a92

**Comment by garys-esri** [comment]
#115 is fixed in 68f0df537d855cc38ff7b00a6b121d7ee223d273

Now I just need to work with @jrweakland on debugging the spot report crash, since I cannot reproduce it on my three devices.

**Comment by garys-esri** [comment]
The spot report crash is fixed and documented in 610f5cefc5a3248eaccb936061d05e48827e8d99. Even if the user does not make the change we suggest (i.e. uncheck "Don't Keep Activities"), the app should not crash, though it will reset its layers when the user goes to the spot report or settings form and back to the map.

@jrweakland, I will get you another build to test soon.

**Comment by garys-esri** [comment]
@jrweakland, can this issue be closed now?

**Comment by jrweakland** [comment]
All of my original issues have been addressed by @garys-esri
