### ISSUE TITLE
Missing Download for 1.0.0 on Esri Downloads Website

### ISSUE THREAD

**Issue by jrweakland** [Esri/squad-leader-android#129]
The following link does not have the zip file

http://www.esri.com/apps/products/download/index.cfm?fuseaction=download.main&downloadid=1703

![image](https://cloud.githubusercontent.com/assets/5739155/9979770/1e169f0e-5f32-11e5-90ec-82d2431ef645.png)

**Comment by jrweakland** [comment]
@lfunkhouser - have we found this file yet?

**Comment by conklinbd** [comment]
Since we do not have the original release notes and source code for this version, we don't we just remove it.

**Comment by joebayles** [comment]
The download has been up there the whole time, but for some reason there's an break between the location and the download file... item 1703 is SquadLeader1.0.0.zip, but location 1703 links to ArcGIS Viewer 3.3 for Silverlight (32-bit) - Japanese. I'm trying to troubleshoot it now.

**Comment by joebayles** [comment]
Fixed.
