### ISSUE TITLE
Add MIL-STD-2525C message layer

### ISSUE THREAD

**Issue by garys-esri** [Esri/squad-leader-android#7]
Vehicle Commander lets you open an XML file of GeoMessages and render them in a MIL-STD-2525C layer implemented as a graphics layer. Squad Leader should allow the same.

**Comment by jrweakland** [comment]
Backlog item - https://app.asana.com/0/23019535413944/23192032216726

**Comment by BobBooth** [comment]
New backlog item: 
https://app.asana.com/0/45762048930961/45762048930968
