### ISSUE TITLE
Have device ignore it's own position

### ISSUE THREAD

**Issue by dfoll** [Esri/squad-leader-android#81]
Currently there is a setting to broadcast your position to all listening devices, which you need to have turned on, so that other devices can see your position. This is fine. However this also makes your own device display you as a unit in the display on top of the blue dot that is your position. It would be nice if this did not show. I know this is minor, but this is just a small change that would make things look cleaner, when you have time to make the change.

**Comment by dfoll** [comment]
@garys-esri i checked this out. i made sure that position reports was checked, and confirmed that it was only showing the blue location dot, and not the unit symbol for the position of the device. the only thing i didn't look at was with other units broadcasting their position. i'll need to wait to grab a router from avi when he gets back, for that. is there anything else you needed tested on squadleader? i thought there were a couple more, but planbox got cleared out, and this is the only thing i see in asana related to squadleader

**Comment by garys-esri** [comment]
Thanks @dfoll. This is the only issue to test for now.

**Comment by dfoll** [comment]
ok cool. up to you if you want to mark it closed now, or hang on to make sure nothing crazy happens when it's listening for simulated messages

**Comment by jrweakland** [comment]
Backlog item - https://app.asana.com/0/23019535413944/23019535413977

**Comment by garys-esri** [comment]
I'm fairly confident, so I will go ahead and mark it closed. Thanks for the help!
