### ISSUE TITLE
Interactive Viewshed

### ISSUE THREAD

**Issue by garys-esri** [Esri/squad-leader-android#96]

**Comment by jrweakland** [comment]
Backlog item - https://app.asana.com/0/23019535413944/23019535413977

**Comment by garys-esri** [comment]
This is implemented in 4b476419dde014acb33ffffe9e2da25141657d4b. @jrweakland will test when the other 3.0.0 issues are addressed. I will assign it to him at that time.

**Comment by garys-esri** [comment]
@jrweakland, aside from #115 and #116, does the viewshed work to your satisfaction?

**Comment by garys-esri** [comment]
#115 and #116 are fixed. I will post a new build after we fix #117.
